### ISSUE TITLE
Changes to createprop action.

### ISSUE THREAD

**Issue by dallasjohnson** [eosdac/dacproposals#10]
* The pay amount should actually be an `extendedAsset`
* Add check for the missing symbol
* Add check for negative amount
* Add check for potentially invalid arbitrator.

**Comment by piecesnbits** [comment]
maybe also make the content_hash optional

**Comment by dallasjohnson** [comment]
@piecesnbits forgot to mention that. Are we sure we want that to be optional. It feels like something that would maintain the integrity of the approved WP. That actually feels more important to me than the other text fields in the action. @michaeljyeates what do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by piecesnbits** [comment]
the data on chain is not mutable so unless the hash is an ipfs hash or the trx_id it's redundant.

**Comment by dallasjohnson** [comment]
I was thinking more like an IPFS hash or similar to what’s we do for members terms so we don’t need to put everything possibly images or design documents through the chain fields. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dallasjohnson** [comment]
Maybe I’m overthinking it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by piecesnbits** [comment]
yeah if we could retrieve the content with the hash then it would make sense. however atm the contract checks for length == 32. but an ipfs hash is usually 32 bytes. So I was thinking that you wanted to use the content_hash for an md5 of the actual content. but the content is already on chain so it can be verified without hash. the constitution isn't on chain so then it makes sense to have a hash stored.

**Comment by piecesnbits** [comment]
so maybe we can populate the hash field with the trx_id on chain. like with the profiles?

**Comment by dallasjohnson** [comment]
All these changes have been done and are being tested. In addition there is now an `uint64_t`  that is required as tyhe primary key for the proposal. This should generated off-chain and then is injects to the action which will ensure there are no key collisions in the action.
