### ISSUE TITLE
Optional USD payment?

### ISSUE THREAD

**Issue by afurmanczyk** [eosdac/dacproposals#11]
If USD is wanted for optional payment, Carbon USD (https://www.carbon.money/) is an EOS based "Stable coin".

It can be traded on: https://eos.bancor.network/

**Comment by dallasjohnson** [comment]
Anything that can be expressed as an `extended_asset` and using the same actions as eosio.token for transfers can be used in the dacproposals. This still requires the custodians to agree to support the proposed token via the approvals for that payment but technically they can.
