### ISSUE TITLE
Voting Algorithm

### ISSUE THREAD

**Issue by dallasjohnson** [eosdac/dacproposals#19]
In all cases the current custodians would vote to approve a worker proposal (WP)

Current code and design:

Option 1:
Each custodian would vote `yes` or `no` for a wp. There is a minimum number of votes required to validate a WP election and percentage of `yes` votes required to approve a WP.

Problem:
Eg. 6 votes required with a 51% threshold to approve:
Currently there are 5 yes votes and the next voter wants to vote no, however if they do they will inadvertently approve the WP because it will reach 6 votes > 51% yes.
Having recognised this they could abstain from voting and prevent approval. This may also hide the fact that there could be another 7 voters who want to vote `no` but cannot all vote simultaneously therefore none of them vote for the same reason as the first `no` voter.

Option 2:

Follow the same rules as above but have secret votes. 

Problem:

Not known to be possible on a public blockchain or without a centralised solution off chain.

Option 3:

Same rules as above but with a fixed time frame to allow for enough potential no voters to vote without triggering approval. 

Problem:

The time frame may be too short and some custodians may miss an opportunity to vote even though they have an opinion. 
The timeframe could be too long so be inefficient for the dac or have workers leave from impatience or other work offers. 
The time may expire still with a minimum voter turnout then we have wasted time and still have no result. 
The reason for low voter turnout could be due to some custodians not feeling qualified to vote for a particular WP due to lack of technical expertise. 

Option 4:
As above rules but with addition of an abstain vote. This would signal to the dac that they would like a decision on the WP but defer their vote to another expert on the team who they trust. Then the percentage of yes votes would be calculated from the yes vs no votes and the abstain votes would help increase the numbers for the required threshold. Then a result could be reached sooner than the time expiry and it would be clear that enough custodians had considered the WP if only to abstain. Keep in mind that as more information becomes available a custodian can change their vote as long as the ‘startwork’ action has not been run. 

Problem:
It’s getting more complicated and may be hard for all custodians to understand these rules. 
The required percentage (or number of votes if not expressed as percentage) must be greater than half the voting population to avoid a minority grabbing an early unrepresentative voting result.

**Comment by dallasjohnson** [comment]
@piecesnbits Addition
Option 5:

Keep things simple and only tally the YES votes (no voting participation threshold). With this option a WP only can get approved if x amount of the custodians vote YES within the timeframe the voting is open (same as with msigs). If the YES threshold is not met in this timeframe the WP get denied. I suggest having the threshold set to a minimum of 50% +1. In case of eosDAC this would be 7 required YES votes. The NO votes can be recorded too for letting all custodians being able to express their decision. However, the wp only can get approved when enough yes votes are collected.

**Comment by dallasjohnson** [comment]
Saro's next additional point:

I think this is the best option. If 7 Custodians vote in favour, that signals both that enough attention has been put on the proposal and enough approval. As noted this will require a deletion of the concept of a quorum for Custodian voting in the Const., but I think this is okay.

Ideally we would allow a no vote, so that Custodians can register their disapproval with something. - Saro

**Comment by dallasjohnson** [comment]
OK, I’m happy to go with the simpler changes as detailed in Option 5.
The changes I will make

**Comment by lukestokes** [comment]
@michaeljyeates Can you weigh in on this, please? The original design document had abstain and a token lockup and your comments seemed to indicate a "No" was more along the lines of "Mark as Spam" based on your thinking.

As for time delay, I'm personally fine with 30 days. If the DAC can't decide on whether or not to approve a project within 30 days, then they can just resubmit it.

**Comment by dallasjohnson** [comment]
done for now
