### ISSUE TITLE
Arbitrators will need a mechanism to approve a transfer if the DAC doesn’t agree with the claimer

### ISSUE THREAD

**Issue by lukestokes** [eosdac/dacproposals#2]
Captured from a previous meeting: https://docs.google.com/document/d/10hnbzx9vQ5jR5x_kf_u_awvqgnnzDmsH53CEncU82Sc/edit#heading=h.5v4jvdh0icpn

**Comment by dallasjohnson** [comment]
@lukestokes @michaeljyeates Do you think it would be OK to add another action to the proposals contract that could only be called by the arbitrator to override the custodians vote which would simply approve the proposal and the escrow claim? This seems risky and corruptible but I guess if the custodians and the worker jointly trust the arbitrator this should be fine.

**Comment by lukestokes** [comment]
@dallasjohnson The intent was to have a multisig within the code that would include the arbitrator and the worker to transfer the funds. If another action is needed for that, then yes, I'd say let's go ahead and add it.
